language: bash

env:
  global:
  - IMAGE_NAME="spark-k8s-addons"
  - FROM_DOCKER_IMAGE="guangie88/spark-k8s"
  - FROM_PY_DOCKER_IMAGE="guangie88/spark-k8s-py"

matrix:
  include:
  - services: docker
    env:
    - SPARK_VERSION=master-85dafab
    - HADOOP_VERSION=3.2.0
  - services: docker
    env:
    - SPARK_VERSION=2.4.4
    - HADOOP_VERSION=3.1.0

script:
- |-
  docker build . \
    --build-arg FROM_DOCKER_IMAGE \
    --build-arg SPARK_VERSION=${SPARK_VERSION} \
    --build-arg HADOOP_VERSION=${HADOOP_VERSION} \
    -t "${IMAGE_NAME}:${SPARK_VERSION}_hadoop-${HADOOP_VERSION}"

deploy:
  provider: script
  script: bash push-images.sh
  on:
    branch: master

branches:
  only:
  - master
